version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: cricket-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadminDB_Password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./cricket_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:pgadminDB_Password@db:5432/db-name
      - SECRET_KEY=4B208688f40694772a901bdbb9a38f4acbe8bd55471d940c5f3f17ac1954fbL0
    depends_on:
      - db

  frontend:
    build: ./cricket-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: